/**
 * Dynamic favicon at 32×32. Renders the AG monogram only — no wordmark —
 * because the full lockup is unreadable below 80px.
 *
 * Solid brand-primary background, "AG" rendered in white at extra-bold
 * weight with negative tracking. Generated by Next.js at build time via
 * the ImageResponse / Satori pipeline — no external font fetch needed
 * (Satori falls back to a system sans which renders cleanly at this size).
 */
import { ImageResponse } from "next/og";

export const size = { width: 32, height: 32 };
export const contentType = "image/png";

export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: "#013299",
          color: "#ffffff",
          fontSize: 20,
          fontWeight: 900,
          letterSpacing: "-0.06em",
          fontFamily:
            "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
        }}
      >
        AG
      </div>
    ),
    { ...size },
  );
}
